### ISSUE TITLE
New Discord Class update broke theme

### ISSUE THREAD

**Issue by Kenst1092** [Josh65-2201/Discord-Windows-11-theme#84]
## Describe the issue 
The new Discord class update has broken your theme, with elements being sorely out of place

## Expected behavior 
A proper theme with consistent element positioning and sizes

## Steps to reproduce 
On Vencord, follow your auto-update installation steps and auto-apply theme

## Screenshots/video 
![image](https://github.com/Josh65-2201/Discord-Windows-11-theme/assets/20787137/53aac16d-41dc-42e2-a1f4-1fea04b0e94b)

## Versions  
Discord: Stable 279382
Vencord: De9122b
Theme: Discord Windows 11 Theme v0.9.2

**Comment by Josh65-2201** [comment]
Thanks for the report, I'm currently fixing this

**Comment by Josh65-2201** [comment]
The icon issue should be fixed with 0.9.3
